// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/auto-geocode" | "/admin/consults" | "/admin/corrections" | "/admin/facilities" | "/admin/glossary" | "/admin/inquiries" | "/admin/members" | "/admin/partnership" | "/admin/pricing-v2" | "/admin/pricing-v3" | "/admin/reviews" | "/admin/settings" | "/admin/upload" | "/admin/upload/[id]" | "/auth/complete" | "/contact" | "/facility/[id]" | "/facility/[id]/consult" | "/facility/[id]/reviews" | "/facility/[id]/reviews/[reviewId]" | "/faq" | "/glossary" | "/glossary/anchi" | "/glossary/biyong" | "/glossary/bongandang" | "/glossary/bonganham" | "/glossary/chumogongwon" | "/glossary/gongwonmyoji" | "/glossary/hapjang" | "/glossary/hwajang" | "/glossary/ijang" | "/glossary/jandijang" | "/glossary/jayeonjang" | "/glossary/napgol" | "/glossary/sumokjang" | "/history" | "/inquiries" | "/list" | "/menu" | "/myinfo" | "/partnership" | "/privacy" | "/region/[slug]" | "/search" | "/search/[city]/[category]" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/auth" | "/api/admin/consults" | "/api/admin/facilities" | "/api/admin/faqs" | "/api/admin/faqs/[id]" | "/api/admin/inquiries" | "/api/admin/inquiries/count" | "/api/admin/members" | "/api/admin/policies/[type]" | "/api/admin/pricing" | "/api/admin/reviews" | "/api/analyze-pdf" | "/api/analyze-pricing-image" | "/api/auth/delete-account" | "/api/auth/exchange-code" | "/api/auth/send-otp" | "/api/auth/verify-otp" | "/api/bulk-insert-pricing" | "/api/consult" | "/api/contact" | "/api/contact/[id]" | "/api/corrections" | "/api/crawl" | "/api/facilities" | "/api/facilities-v2" | "/api/facilities/[id]" | "/api/facilities/[id]/inquiries" | "/api/facilities/[id]/inquiries/verify" | "/api/facilities/[id]/prices" | "/api/facilities/[id]/review" | "/api/facilities/[id]/view" | "/api/favorites" | "/api/geocode" | "/api/inquiries" | "/api/partnership" | "/api/pricing-export" | "/api/reviews/interact" | "/api/reviews/my" | "/api/save-pricing" | "/api/tool/gemini-save" | "/api/upload" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/%EC%A7%80%EC%97%AD/[[...slug]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/%EC%A7%80%EC%97%AD/[[...slug]]": { "slug"?: string[]; }
  "/about": {}
  "/admin": {}
  "/admin/auto-geocode": {}
  "/admin/consults": {}
  "/admin/corrections": {}
  "/admin/facilities": {}
  "/admin/glossary": {}
  "/admin/inquiries": {}
  "/admin/members": {}
  "/admin/partnership": {}
  "/admin/pricing-v2": {}
  "/admin/pricing-v3": {}
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/upload": {}
  "/admin/upload/[id]": { "id": string; }
  "/api/admin/auth": {}
  "/api/admin/consults": {}
  "/api/admin/facilities": {}
  "/api/admin/faqs": {}
  "/api/admin/faqs/[id]": { "id": string; }
  "/api/admin/inquiries": {}
  "/api/admin/inquiries/count": {}
  "/api/admin/members": {}
  "/api/admin/policies/[type]": { "type": string; }
  "/api/admin/pricing": {}
  "/api/admin/reviews": {}
  "/api/analyze-pdf": {}
  "/api/analyze-pricing-image": {}
  "/api/auth/delete-account": {}
  "/api/auth/exchange-code": {}
  "/api/auth/send-otp": {}
  "/api/auth/verify-otp": {}
  "/api/bulk-insert-pricing": {}
  "/api/consult": {}
  "/api/contact": {}
  "/api/contact/[id]": { "id": string; }
  "/api/corrections": {}
  "/api/crawl": {}
  "/api/facilities": {}
  "/api/facilities-v2": {}
  "/api/facilities/[id]": { "id": string; }
  "/api/facilities/[id]/inquiries": { "id": string; }
  "/api/facilities/[id]/inquiries/verify": { "id": string; }
  "/api/facilities/[id]/prices": { "id": string; }
  "/api/facilities/[id]/review": { "id": string; }
  "/api/facilities/[id]/view": { "id": string; }
  "/api/favorites": {}
  "/api/geocode": {}
  "/api/inquiries": {}
  "/api/partnership": {}
  "/api/pricing-export": {}
  "/api/reviews/interact": {}
  "/api/reviews/my": {}
  "/api/save-pricing": {}
  "/api/tool/gemini-save": {}
  "/api/upload": {}
  "/auth/callback": {}
  "/auth/complete": {}
  "/contact": {}
  "/facility/[id]": { "id": string; }
  "/facility/[id]/consult": { "id": string; }
  "/facility/[id]/reviews": { "id": string; }
  "/facility/[id]/reviews/[reviewId]": { "id": string; "reviewId": string; }
  "/faq": {}
  "/glossary": {}
  "/glossary/anchi": {}
  "/glossary/biyong": {}
  "/glossary/bongandang": {}
  "/glossary/bonganham": {}
  "/glossary/chumogongwon": {}
  "/glossary/gongwonmyoji": {}
  "/glossary/hapjang": {}
  "/glossary/hwajang": {}
  "/glossary/ijang": {}
  "/glossary/jandijang": {}
  "/glossary/jayeonjang": {}
  "/glossary/napgol": {}
  "/glossary/sumokjang": {}
  "/history": {}
  "/inquiries": {}
  "/list": {}
  "/menu": {}
  "/myinfo": {}
  "/partnership": {}
  "/privacy": {}
  "/region/[slug]": { "slug": string; }
  "/search": {}
  "/search/[city]/[category]": { "city": string; "category": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
