// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/auto-geocode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auto-geocode">> = Specific
  const handler = {} as typeof import("../../../app/admin/auto-geocode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/consults/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consults">> = Specific
  const handler = {} as typeof import("../../../app/admin/consults/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/corrections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/corrections">> = Specific
  const handler = {} as typeof import("../../../app/admin/corrections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/facilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/facilities">> = Specific
  const handler = {} as typeof import("../../../app/admin/facilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/glossary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/glossary">> = Specific
  const handler = {} as typeof import("../../../app/admin/glossary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../../app/admin/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members">> = Specific
  const handler = {} as typeof import("../../../app/admin/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/partnership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partnership">> = Specific
  const handler = {} as typeof import("../../../app/admin/partnership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pricing-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing-v2">> = Specific
  const handler = {} as typeof import("../../../app/admin/pricing-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pricing-v3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing-v3">> = Specific
  const handler = {} as typeof import("../../../app/admin/pricing-v3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/upload/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/upload/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/upload/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/upload">> = Specific
  const handler = {} as typeof import("../../../app/admin/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/complete">> = Specific
  const handler = {} as typeof import("../../../app/auth/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/facility/[id]/consult/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facility/[id]/consult">> = Specific
  const handler = {} as typeof import("../../../app/facility/[id]/consult/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/facility/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facility/[id]">> = Specific
  const handler = {} as typeof import("../../../app/facility/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/facility/[id]/reviews/[reviewId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facility/[id]/reviews/[reviewId]">> = Specific
  const handler = {} as typeof import("../../../app/facility/[id]/reviews/[reviewId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/facility/[id]/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facility/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../../app/facility/[id]/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/anchi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/anchi">> = Specific
  const handler = {} as typeof import("../../../app/glossary/anchi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/biyong/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/biyong">> = Specific
  const handler = {} as typeof import("../../../app/glossary/biyong/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/bongandang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/bongandang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/bongandang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/bonganham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/bonganham">> = Specific
  const handler = {} as typeof import("../../../app/glossary/bonganham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/chumogongwon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/chumogongwon">> = Specific
  const handler = {} as typeof import("../../../app/glossary/chumogongwon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/gongwonmyoji/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/gongwonmyoji">> = Specific
  const handler = {} as typeof import("../../../app/glossary/gongwonmyoji/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/hapjang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/hapjang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/hapjang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/hwajang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/hwajang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/hwajang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/ijang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/ijang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/ijang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/jandijang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/jandijang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/jandijang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/jayeonjang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/jayeonjang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/jayeonjang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/napgol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/napgol">> = Specific
  const handler = {} as typeof import("../../../app/glossary/napgol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary">> = Specific
  const handler = {} as typeof import("../../../app/glossary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/sumokjang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary/sumokjang">> = Specific
  const handler = {} as typeof import("../../../app/glossary/sumokjang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inquiries">> = Specific
  const handler = {} as typeof import("../../../app/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/list">> = Specific
  const handler = {} as typeof import("../../../app/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../../app/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/myinfo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/myinfo">> = Specific
  const handler = {} as typeof import("../../../app/myinfo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partnership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partnership">> = Specific
  const handler = {} as typeof import("../../../app/partnership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/region/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/region/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/region/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/[city]/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/[city]/[category]">> = Specific
  const handler = {} as typeof import("../../../app/search/[city]/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/consults/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/consults">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/consults/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/facilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/facilities">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/facilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/faqs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/faqs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/faqs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/faqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/faqs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/faqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/inquiries/count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries/count">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/inquiries/count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/members">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/policies/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/policies/[type]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/policies/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pricing">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-pricing-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-pricing-image">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-pricing-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/delete-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/delete-account">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/delete-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/exchange-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/exchange-code">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/exchange-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/bulk-insert-pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-insert-pricing">> = Specific
  const handler = {} as typeof import("../../../app/api/bulk-insert-pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/consult/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consult">> = Specific
  const handler = {} as typeof import("../../../app/api/consult/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/corrections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/corrections">> = Specific
  const handler = {} as typeof import("../../../app/api/corrections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/crawl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crawl">> = Specific
  const handler = {} as typeof import("../../../app/api/crawl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities-v2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities-v2">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities-v2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]/inquiries">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/inquiries/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]/inquiries/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/inquiries/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]/prices">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]/review">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities/[id]/view">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/facilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facilities">> = Specific
  const handler = {} as typeof import("../../../app/api/facilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites">> = Specific
  const handler = {} as typeof import("../../../app/api/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode">> = Specific
  const handler = {} as typeof import("../../../app/api/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiries">> = Specific
  const handler = {} as typeof import("../../../app/api/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partnership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partnership">> = Specific
  const handler = {} as typeof import("../../../app/api/partnership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pricing-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing-export">> = Specific
  const handler = {} as typeof import("../../../app/api/pricing-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reviews/interact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/interact">> = Specific
  const handler = {} as typeof import("../../../app/api/reviews/interact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reviews/my/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/my">> = Specific
  const handler = {} as typeof import("../../../app/api/reviews/my/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/save-pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/save-pricing">> = Specific
  const handler = {} as typeof import("../../../app/api/save-pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tool/gemini-save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tool/gemini-save">> = Specific
  const handler = {} as typeof import("../../../app/api/tool/gemini-save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
